version: '3'
services:
  supplier:
    image: ahmedmissaoui/devops_indiv:latest
    build: .
    depends_on:
      - mysqldb
    restart: on-failure
    ports:
      - "8085:8085"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - my-network
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db:/var/lib/mysql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db:
  .m2: