version: '2'
services:
  invoice:
    build:
      context: .
    image: ahmedmissaoui/devops_indiv:latest
    ports:
      - "8088:8088"
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: devops
      MYSQL_USER: sa
      MYSQL_PASSWORD: sa
    ports:
      - "3306:3306"